refactor: Rename src/manifest.d.ts to manifest.ts
If types should be accessible to external consumers of UI5 linter, they
must be located in .ts files since only those can be imported.

Currently, building UI5 linter as a dependency yields the following
error:
```
/ui5-linter/lib/linter/ui5Types/fix/Fix.d.ts:5:46 - error TS2307:
Cannot find module '../../../manifest.js' or its corresponding type declarations.
```

Also see
`https://github.com/microsoft/TypeScript/issues/36971#issuecomment-590473898`:

> Your project itself should not be hand-authoring .d.ts files you
> intend to be seen by consumers of your project; this is why it's legal
> to write "only types" in a .ts file